kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-utils-operator
rules:
# Operator Business Logic
- apiGroups:
  - ""
  resources:
  - services
  - events
  - secrets
  verbs:
  - "*"
# Operator Business Logic
- apiGroups:
  - " route.openshift.io"
  resources:
  - routes
  verbs:
  - "*"  
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-utils-operator
rules:
# - apiGroups:
#   - ""
#   resources:
#   - namespaces
#   verbs:
#   - get
# leader election   
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"  
#Metrics  
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"  
# Metrics  
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
# Metrics  
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - cert-utils-operator
  verbs:
  - "update"

